version: '3.7'

services:
  db:
    container_name: leaglecup_database
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./database/leaglecup.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: leaglecup
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  phpmyadmin:
    container_name: leaglecup_phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      PMA_HOST: db:3306

  web:
    container_name: leaglecup_web
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "80:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: leaglecup
      WORDPRESS_TABLE_PREFIX: lglcp_
    volumes:
      - ./web:/var/www/html

volumes:
    db_data: {}
